version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_HUBSPOT_TOKEN=${NEXT_PUBLIC_HUBSPOT_TOKEN}
    restart: unless-stopped