version: '3.8'
services:
  lenderify:
    build:
      context: .
      tags:
        - "highergroundstudio/lenderify"
    image: highergroundstudio/lenderify
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /tmp/uploads:/tmp/uploads
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    user: "1000:1000"
    privileged: true
